### ISSUE TITLE
Android 4.1 crash at server startup

### ISSUE THREAD

**Issue by ka223** [ppareit/swiftp#79] opened 2016-08-13 20:34 UTC
Hi,
the server crashes / app closes by starting the ftp server on android 4.1.

The app is working fine at my other CM13 device.

FTP Server version 2.12.0

The older version 2.10.2 is working at android 4.1.

**Comment by Vrihub** [comment] 2016-10-12 21:02
This might or might not be related, but I am also experiencing crashes ("Unfortunately FTPserver has stopped") as soon as I start the server (version 2.12.0 from F-droid, on android 4.2.2, samsung phone): the server starts for a very short time (and I can connect with a client if I am quick enough), then the error message appears, and the server stops.

The problem happens randomly, about once a week (I use the app a couple of times a day); it seems to happen more frequently if I turn off the wifi network and then I turn it on again. Also, while the wifi is turned off (and the server is obviously off) the ftpserve "popup" remains visible in the notification pull-down menu, and there is no way to clear it, by pressing the "X Stop server" icon. When I turn the wifi on again, sometimes the problem happens. I also have the impression that the problem is more frequent when I have the "autoconnect" setting on, but I'm not really sure about this.

The only way I found to have the server starting regularly again is by rebooting the phone. Force-stopping the app from the android "application settings" (or killing the process using OS monitor), or even uninstalling and re-installing the app won't make the problem go away: rebooting is the only solution.

This bug started happening with FTPserver free 2.12.0 from the F-droid repository, previous versions including 2.10.2 worked flawlessly.

**Comment by ppareit** [comment] 2017-01-07 15:08
Version 2.10.x was still build with Eclipse. Since then the project was converted to gradle. This was a complete upgrade of tools. Next to that, multiple changes where made to the low level parts of the server. From reviewing, I can't pinpoint where the problem could be. This could well be a problem with the apk from fdroid. Could you provide a trace, for instance by running 'adb logcat'? (before posting logcat, check for sensitive data, or mail me using the feedback option inside the app)

**Comment by Vrihub** [comment] 2017-01-07 20:24
I don't know what 'adb logcat' means. If you can point me to any documentation about that, I'll be glad to help.

**Comment by Vrihub** [comment] 2017-02-01 20:40
>  I am also experiencing crashes ("Unfortunately FTPserver has stopped") as soon as I start the server (version 2.12.0 from F-droid, on android 4.2.2, samsung phone)

FYI, upgrading to version 2.13.1 (from google store) fixed my problem.

**Comment by ppareit** [comment] 2017-02-01 20:49
I've checked the versions on f-droid (https://f-droid.org/wiki/page/be.ppareit.swiftp_free) and it seems that it fails to build because they need to build twofortyfouram's sdk. While the code for that is on github, I'll check to see if it is possible to adapt the fdroid build variant to a version that does not use that library.

I'll close this issue as it seems to concern an old version of swiftp.

**Closed by ppareit** 2017-02-01 20:49 UTC

**Comment by Vrihub** [comment] 2017-07-16 10:02
FYI, I've experienced my problem again, but very rarely (see below), on swiftp free 2.15.0 (f-droid repository) and android 4.2.2.

The symptoms are the same already described in https://github.com/ppareit/swiftp/issues/79#issuecomment-253338281 (crash at startup, reboot is the only solution).

The only news: it seems to happen after long periods **without** rebooting the phone (10 days or more); please note that I use the server more than twice a day, autoconnecting with a trusted wifi network.

If you can think about any reason why a long uptime could cause this problem, this might be a hint.

**Comment by ppareit** [comment] 2017-07-17 07:53
Thanks for bringing this back to my attention!

I've been thinking about this and one thing that might crash the phone
that is in ftp server is the NSD code. NsdManager was introduced in api
level 16 (android 4.1) and was notorious for been buggy. I suppose
current android versions are much more stable in that regard.

I'll prepare a beta version for you that has an option to disable NSD
support. Leave your google email for me (email me using the feedback
option in the app), so I can add you to the beta channel.

**Comment by Vrihub** [comment] 2017-07-18 14:12
Fortunately it's not the phone crashing, just the app. Anyway since it's now a very rare problem, and since it's good practice to reboot the phone every few days (I've seen other apps freezing/slowing down after a long uptime), I think I'll live with it, and you may focus on more urgent bugs.

**Comment by ka223** [comment] 2017-08-31 17:54
@ppareit 
The app is crashing at android 4.1, installed from google play, version 2.16.00(4.1.1-16)

Here is a logcat, maybe can help to identify the problem.
https://pastebin.com/aeRPaRrz

**Comment by ashutoshgngwr** [comment] 2017-09-01 23:44
`setShownWhen()` & `setVisibility()` were added to `Notification.Builder()` in API Level 17 (Android 4.2). Since you're running swiftp on Android 4.1, hence the crash.

**Comment by ashutoshgngwr** [comment] 2017-09-01 23:57
`setShownWhen()` & `setVisibility()` were added to `Notification.Builder()` in API Level 17 (Android 4.2) and 21 (Android 5.0) respectively. Since you're running swiftp on Android 4.1, hence the crash.

Thanks for that logcat @ka223

**Comment by ashutoshgngwr** [comment] 2017-09-02 01:08
@ka223 I have wrote a solution for this issue. Can you build FTP Server from [my fork](https://github.com/ashutoshgngwr/swiftp) and tell me if it works? I don't have a device or emulator that runs Android 4.1.
